services:
  - type: web
    name: elegant-court-kyoto
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
